### ISSUE TITLE
Feature: Project Organization

### ISSUE THREAD

**Issue by AndrewCMonson** [AndrewCMonson/oscar#15]
# Summary
Users should be able to organize their chats by project to ensure overall organization and separation of concerns.

## Proposed Solution
Implement a UI component on the "Chat" page that selects which project they are discussing and sends that information to the assistant.

## Benefits
Ensures there are no overlap between projects and a clear separation of tasks.

## Acceptance Criteria

- [x] There is a projects list UI on the Chat page that pulls the user's projects and displays them
- [x] When prompted, the assistant can specify which project they are helping with
- [x] User can create new projects via UI interaction

## Notes
Assigning projects to each have their own conversation/chat helps with the workflow immensely. In the future as the assistant becomes more advanced, there may be room to remove this feature, but ultimately it should remain as a pillar of the application.

## Linked issues:
#7 Feature: User Interface
