### ISSUE TITLE
Enhancement: Centralized Types Location

### ISSUE THREAD

**Issue by AndrewCMonson** [AndrewCMonson/oscar#19]
# Summary
Currently, both the client and api have separate types that overlap due to graphql codegen.

## Proposed Solution
Implement a "Types" package to store all types for ease of access. Along with this, create a root codegen config to type graphql once.

## Benefits
Centralized types and use of the DRY principle

## Acceptance Criteria

- [x] Single codegen.ts config file in root 
- [ ] Types package alongside api/client packages
- [x] Ability to codegen from all directories

## Notes
N/A

## Linked issues:
#7 This will be resolved within the User Interface Feature request

**Comment by AndrewCMonson** [comment]
This was resolved with #7 Feature User Interface
