### ISSUE TITLE
Feature: User Interface

### ISSUE THREAD

**Issue by AndrewCMonson** [AndrewCMonson/oscar#7]
# Summary
Currently, the user interface is barebones and used only for testing the functionality of the assistant. It is a pure send and receive chat box and button.

## Proposed Solution
Implement a user interface that allows the user to interact with the assistant, view their projects/conversations and update their preferences.

## Benefits
This is the first iteration of user facing functionality. It will allow the application to be used and tested by different users.

## Acceptance Criteria

- [x] User can view their projects and change conversations on a project basis
- [x] User can view and update their preferences
- [x] User can interact with the assistant via natural language in an organized, user friendly chatbox.

## Notes
- ShadCN is being used and already implemented in the project, so components should be built and used with that in mind.
- This is simply the first iteration and meant to be an MVP. Any additional features beyond described in this issue will be considered a different issue.

## Linked issues:
#6 Development: User Authentication - once User Auth is implemented, login and signup screens will be added to the UI.
